{ config, pkgs, lib, ... }:

let
  dotfiles = ../config;
in
{
  home.username = "ziyadev";
  home.homeDirectory = "/home/ziyadev";
  home.stateVersion = "24.11";

  # Let home-manager manage itself.
  programs.home-manager.enable = true;

  # Packages that mirror the Omarchy/Arch install. Trim/extend as you
  # discover what NixOS actually needs vs. what pacman pulled in for you
  # automatically.
  home.packages = with pkgs; [
    alacritty
    foot
    kitty
    ghostty
    btop
    lazygit
    tmux
    starship
    fcitx5
    neovim
    mise
  ];

  programs.git = {
    enable = true;
    # Real config content is symlinked in below from config/git; this just
    # makes sure git itself is installed.
  };

  # mpv-mpris is a script, not a binary — mpv only picks it up when told to
  # load it, not from being present on PATH.
  programs.mpv = {
    enable = true;
    scripts = [ pkgs.mpvScripts.mpris ];
  };

  # ---------------------------------------------------------------------
  # Straight symlinks of your personal ~/.config overrides (../config —
  # diffed against Omarchy's own skeleton in ../vendor/omarchy/config, so
  # this really is just your customizations plus the handful of dirs that
  # were already stock). ../modules/omarchy.nix is what makes hypr/*.lua
  # actually load: it vendors Omarchy's own Lua defaults + Quickshell shell
  # to /usr/share/omarchy and sets OMARCHY_PATH, which is what
  # hyprland.lua's `dofile`/`require` calls need. See README.md.
  #
  # monitors.lua/monitors.conf here were generated by nwg-displays for THIS
  # laptop's actual screen — check them once on the new machine rather than
  # assuming the resolution/scale/layout still applies.
  # ---------------------------------------------------------------------
  xdg.configFile = {
    "hypr".source = "${dotfiles}/hypr";
    "alacritty".source = "${dotfiles}/alacritty";
    "foot".source = "${dotfiles}/foot";
    "kitty".source = "${dotfiles}/kitty";
    "ghostty".source = "${dotfiles}/ghostty";
    "nvim".source = "${dotfiles}/nvim";
    "tmux".source = "${dotfiles}/tmux";
    "btop".source = "${dotfiles}/btop";
    "mise".source = "${dotfiles}/mise";
    "lazygit".source = "${dotfiles}/lazygit";
    "git".source = "${dotfiles}/git";
    "nwg-displays".source = "${dotfiles}/nwg-displays";
    "gtk-3.0".source = "${dotfiles}/gtk-3.0";
    "fcitx5".source = "${dotfiles}/fcitx5";
    "autostart".source = "${dotfiles}/autostart";
    "omarchy".source = "${dotfiles}/omarchy";
    "starship.toml".source = "${dotfiles}/starship.toml";
    "mimeapps.list".source = "${dotfiles}/mimeapps.list";
    "hyprland-preview-share-picker".source = "${dotfiles}/hyprland-preview-share-picker";
    "imv".source = "${dotfiles}/imv";
    "wireplumber".source = "${dotfiles}/wireplumber";
    "xournalpp".source = "${dotfiles}/xournalpp";
    "herdr".source = "${dotfiles}/herdr";
    "opencode".source = "${dotfiles}/opencode";
  };
}
